version: '2'

services:

  jenkins:
    container_name: jenkins-scm
    image: netoht/jenkins-scm:latest
    ports:
      - "8080:8080"
    environment:
      - "SCM_REPOSITORY=scm:git:https://netoht:xxxxxxxx@github.com/netoht/scm-sync-test.git"
      - "SCM_BRANCH=master"
      - "JAVA_OPTS=-Djenkins.install.runSetupWizard=false"